export const ENV_SYSTEM = import.meta.env;

export const FIREBASE_CONFIG = {
  API_KEY: ENV_SYSTEM.VITE_API_KEY,
  AUTH_DOMAIN: ENV_SYSTEM.VITE_AUTH_DOMAIN,
  DATABASE_URL: ENV_SYSTEM.VITE_DATABASE_URL,
  PROJECT_ID: ENV_SYSTEM.VITE_PROJECT_ID,
  STORAGE_BUCKET: ENV_SYSTEM.VITE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: ENV_SYSTEM.VITE_MESSAGING_SENDER_ID,
  APP_ID: ENV_SYSTEM.VITE_APP_ID,
  MEASUREMENT_ID: ENV_SYSTEM.VITE_MEASUREMENT_ID,
};

export const STATUS_SLICE_STORE = {
  IDLE: 'Inactivo',
  LOADING: 'Cargando',
  FULLFILLED: 'Exitoso',
  FAILED: 'Fallido',
};

export const USER_REACTION = {
  LIKE: 'like',
  DISLIKE: 'unlike',
};

export const USER_ROLE = {
  ADMINISTRATOR: 'admin',
  USER: 'user',
};

export const TYPE_CONTENT = {
  TOPIC: 'topic',
  COMMENT: 'comment',
};

export const TABS_USER = {
  TOPICS: 'TOPICS',
  MESSAGES: 'MESSAGES',
};
